# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-02 09:38
from __future__ import unicode_literals

import Planets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Planets.models.upload_image_path)),
            ],
        ),
    ]
